#ifndef QT_LOGGING_CONFIG_H
#define QT_LOGGING_CONFIG_H

#include <QLoggingCategory>
#include <QDebug>

// Disable Qt's internal JPEG corruption warnings
// These warnings are generated by Qt's image decoder when camera stream has issues
// but they don't affect functionality - they're just noise

// Create a custom logging category to control Qt's internal logs
Q_LOGGING_CATEGORY(qtImageIO, "qt.gui.imageio", QtWarningMsg)

// Function to disable Qt's internal JPEG corruption logs
inline void disableQtJPEGCorruptionLogs() {
    // Set the logging level for qt.gui.imageio to only show critical messages
    QLoggingCategory::setFilterRules("qt.gui.imageio.warning=false");
    QLoggingCategory::setFilterRules("qt.gui.imageio.jpeg=false");
    
    // Alternative approach: disable all qt.gui.imageio logs
    QLoggingCategory::setFilterRules("qt.gui.imageio.*=false");
}

// Function to enable Qt's internal JPEG corruption logs (for debugging)
inline void enableQtJPEGCorruptionLogs() {
    QLoggingCategory::setFilterRules("qt.gui.imageio.*=true");
}

#endif // QT_LOGGING_CONFIG_H
